services:
  - type: web
    name: sos-alert-system
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn sos_project.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: sos-alert-system.onrender.com
      - key: DB_NAME
        fromDatabase:
          name: sos-alert-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: sos-alert-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sos-alert-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: sos-alert-db
          property: host
      - key: DB_PORT
        value: "5433"

databases:
  - name: sos-alert-db
    databaseName: sos_alerts_db
    user: sos_alert_user
    plan: free
